<?php

namespace rucher\RucheBundle\Entity;

/**
 * RucheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RucheRepository extends \Doctrine\ORM\EntityRepository
{
}
