ruche_homepage:
    path:     /home/{id}
    defaults: { _controller: RucheBundle:Default:index }

add_ruche:
    path:     /home
    defaults: {_controller: RucheBundle:AjoutRuche:index }

show_ruche:
    path:     /ruche
    defaults: {_controller: RucheBundle:AfficherRuche:index }

add_Intervention:
    path:     /addInterv
    defaults: {_controller: RucheBundle:AddInterv:index }

delete_Ruche:
    path:     /deleteRuche
    defaults: {_controller: RucheBundle:DeleteRuche:index }

liste_Ruche:
    path:     /listRuches
    defaults: {_controller: RucheBundle:ListeRuches:index }


