<?php

namespace rucher\loginBundle\Entity;

/**
 * apiculteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class apiculteurRepository extends \Doctrine\ORM\EntityRepository
{
}
